version: '3'

services:

  #-----------------------------#
  #      Kafka | Zookeeper      #
  #-----------------------------#

  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:7.0.10.arm64
    container_name: kafka-zookeeper
    restart: on-failure
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  #--------------------------#
  #      Kafka | Broker      #
  #--------------------------#

  kafka-broker:
    image: confluentinc/cp-kafka:7.0.10.arm64
    container_name: kafka-broker
    restart: on-failure
    expose:
      - 9092
    depends_on:
      - kafka-zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-broker:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1

  #--------------------#
  #     Kafka | UI     #
  #--------------------#

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    restart: on-failure
    ports:
      - 8800:8080
    depends_on:
      - kafka-broker
    environment:
      KAFKA_CLUSTERS_0_NAME: keylogger-monitor
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: kafka-zookeeper:2181

  #-----------------#
  #      MySQL      #
  #-----------------#

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: "no"
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
      - $PWD/server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_DATABASE=keylogger_monitor
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PSW}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PSW}

  #-------------------------------#
  #      Spring Boot - Server     #
  #-------------------------------#

  server:
    image: maven:3-amazoncorretto-21-debian
    container_name: server
    restart: on-failure
    working_dir: /usr/src/app/
    command: "mvn clean validate compile test spring-boot:run"
    ports:
      - 6000:6000
    volumes:
      - $PWD/server:/usr/src/app/
    depends_on:
      - kafka-broker
      - mysql-db
    environment:
      - AES_KEY=${AES_KEY}
      - KAFKA_URL=kafka-broker:9093
      - MYSQL_URL=jdbc:mysql://mysql-db:3306/keylogger_monitor
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PSW=${MYSQL_PSW}

  #-------------------------#
  #      Elasticsearch      #
  #-------------------------#

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: elasticsearch
    restart: on-failure
    ports:
      - 9200:9200
    volumes:
      - es001-data:/usr/share/elasticsearch/data/
    environment:
      - node.name=es001
      - discovery.type=single-node
      - cluster.name=elasticsearch-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  #----------------------------#
  #      Spark - Metadata      #
  #----------------------------#

  spark-metadata:
    image: jupyter/pyspark-notebook:spark-3.1.2
    container_name: spark-metadata
    restart: on-failure
    working_dir: /usr/app/src/
    volumes:
      - $PWD/spark-metadata/src:/usr/app/src
      - $PWD/spark-metadata/titles:/usr/app/src/titles
    environment:
      - KAFKA_URL=kafka-broker:9093
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - kafka-zookeeper
      - kafka-broker
      - elasticsearch
    command: >
      bash -c "
      pip3 install --no-cache-dir pyspark elasticsearch deep_translator requests && 
      spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.1 --master local[4] cluster.py"

  #----------------------------#
  #      Grafana - Charts      #
  #----------------------------#

  grafana-charts:
    image: grafana/grafana:8.2.6
    container_name: grafana-charts
    restart: on-failure
    user: "0:0"
    ports:
      - 8888:3000
    depends_on:
      - elasticsearch
    environment:
      - GRAFANA_USER=${GRAFANA_USER}
      - GRAFANA_PASSWORD=${GRAFANA_PSW}
      - GF_INSTALL_PLUGINS=magnesium-wordcloud-panel,grafana-worldmap-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - $PWD/grafana-charts/certs:/etc/grafana/certs
      - $PWD/grafana-charts/provisioning:/etc/grafana/provisioning
      - $PWD/grafana-charts/grafana.ini:/etc/grafana/grafana.ini
      - $PWD/grafana-charts/dashboard.json:/var/lib/grafana/dashboards/dashboard.json

  #-----------------------------#
  #      NodeJs - Frontend      #
  #-----------------------------#

  node-ui:
    image: node:19-alpine3.16
    container_name: node-ui
    restart: on-failure
    working_dir: /home/app/
    command: sh -c "npm install && node app.js"
    ports:
      - 8080:443
    volumes:
      - $PWD/node-ui:/home/app/
    depends_on:
      - mysql-db
      - grafana-charts
    environment:
      - DB_DIALECT=mysql
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER}
      - DB_PSW=${MYSQL_PSW}
      - DB_NAME=keylogger_monitor

volumes:
  mysql-data:
  es001-data:
  grafana-data: